baseURL = "https://cascadia-systems.institute/"
languageCode = "en-us"
title = "Cascadia Systems Institute"

theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Cascadia Systems Institute"
    description = "Spreading systems awareness in the Cascadia bioregion, and beyond."
    copyright = "&copy;2018 All rights reserved."
    #githubUsername = "#"
    accentTop = "#2b00c8"
    accentBottom = "#006200"
    showBorder = true
    backgroundColor = "white"
    MathJax = false
    font = "Raleway" # should match the name on Google Fonts!
    #highlight = true
    #highlightStyle = "solarized-dark"
    #highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/contact/"
    name = "Contact"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:us@cascadia-systems.institute"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/cascadia-systems-institute/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://github.com/cascadia-systems-institute/"
    name = "github"
    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/cascadia-systems-institute/"
#    name = "linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
